// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vfpuivnzbewiuuwjyewm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcHVpdm56YmV3aXV1d2p5ZXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTEzNzQsImV4cCI6MjA3MzYyNzM3NH0.IrZlLJd69CC5hkDCtsnJNXG-Fy5V6Pu4_PxCeA4IIOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);